server:
   port: 80


spring.flyway.locations: "classpath:db/migration/mysql" 
spring.jpa.database: "MYSQL"
spring.datasource.platform: "mysql"
spring.jpa.show-sql: "true"
spring.datasource.driverClassName: "com.mysql.jdbc.Driver"
spring.datasource.url: "jdbc:mysql://mysql-profile-service:3306/profile-service-db?useSSL=false"
spring.datasource.username: "sa"
spring.datasource.password: "password@123"
spring.jpa.database-platform: "org.hibernate.dialect.MySQL8Dialect"
spring.jpa.hibernate.naming.physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
